set(GHECONTROL_VERSION_MAJOR 0)
set(GHECONTROL_VERSION_MINOR 1)
set(GHECONTROL_VERSION_PATCH 0)
set(GHECONTROL_VERSION "${GHECONTROL_VERSION_MAJOR}.${GHECONTROL_VERSION_MINOR}.${GHECONTROL_VERSION_PATCH}")
